### ISSUE TITLE
environments 

### ISSUE THREAD

**Issue by shileicoding** [zhan8002/PSP-Mal#1]
The environment provided by requirements.txt seems to be true and incorrect, can you provide me the correct environment for requirements.txt?I'd also like to ask if this is the complete program?

**Comment by zhan8002** [comment]
This is already the complete program, except that the sample binaries are not included. The required libraries are already included in the _requirements.txt_, and you can refer the repository [malware_rl](https://github.com/bfilar/malware_rl) if you have problems with the installation.
